### Read all films
@baseUrl = http://localhost:3000
GET {{baseUrl}}/films

### Read all films with a minimum duration of 110 minutes
GET {{baseUrl}}/films?minimum-duration=110

### Create a film
POST {{baseUrl}}/films
Content-Type: application/json

{
    "title": "À la recherche du bonheur",
    "duration": 117,
    "budget": 55,
    "link": "https://www.allocine.fr/film/fichefilm_gen_cfilm=54098.html"
}

### Create a film with missing title
POST {{baseUrl}}/films
Content-Type: application/json

{
    "title": "",
    "duration": 117,
    "budget": 55,
    "link": "https://www.allocine.fr/film/fichefilm_gen_cfilm=54098.html"
}

### Create a film with missing duration
POST {{baseUrl}}/films
Content-Type: application/json

{
    "title": "À la recherche du bonheur",
    "duration": ,
    "budget": 55,
    "link": "https://www.allocine.fr/film/fichefilm_gen_cfilm=54098.html"
}

### Create a film with missing budget
POST {{baseUrl}}/films
Content-Type: application/json

{
    "title": "À la recherche du bonheur",
    "duration": 117,
    "budget": ,
    "link": "https://www.allocine.fr/film/fichefilm_gen_cfilm=54098.html"
}

### Create a film with missing link (empty string)
POST {{baseUrl}}/films
Content-Type: application/json

{
    "title": "À la recherche du bonheur",
    "duration": 117,
    "budget": 55,
    "link": ""
}

### Create another film
POST {{baseUrl}}/films
Content-Type: application/json

{
    "title": "Here Today",
    "duration": 117,
    "budget": 3,
    "link": "https://www.allocine.fr/film/fichefilm_gen_cfilm=277040.html"
}

### Read film with id == 3
GET {{baseUrl}}/films/3

### Read film with id that doesn't exist
GET {{baseUrl}}/films/-500

### Delete film identified by 2
DELETE {{baseUrl}}/films/2

### Update film identified by 3
PATCH {{baseUrl}}/films/3
Content-Type: application/json

{
    "title": "La couleur des sentiments",
    "duration": 130
}

### Update film identified by 2
PATCH {{baseUrl}}/films/2
Content-Type: application/json

{
    "title": "Là-Haut",
    "budget": 150
}

### Update a film with id == 2
PUT {{baseUrl}}/films/2
Content-Type: application/json

{
    "title":"Star Wars: Episode II – Attack of the Clones",
    "duration": 142,
    "budget": 115,
    "link":"https://en.wikipedia.org/wiki/Star_Wars:_Episode_II_%E2%80%93_Attack_of_the_Clones"
}

### Update a film with id == 2 when a parameter is missing
PUT {{baseUrl}}/films/2
Content-Type: application/json

{
    "title":"Star Wars: Episode II – Attack of the Clones",
    "duration": 142,
    "link":"https://en.wikipedia.org/wiki/Star_Wars:_Episode_II_%E2%80%93_Attack_of_the_Clones"
}

### Create new film with ID == 666
PUT {{baseUrl}}/films/666
Content-Type: application/json

{
    "title":"Attack of the beast",
    "duration": 666,
    "budget": 666,
    "link":"https://666"
}